apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudbeaver
  name: cloudbeaver
spec:
  ports:
  - name: http
    port: 8978
    protocol: TCP
    targetPort: 8978
  selector:
    app: cloudbeaver
  sessionAffinity: None
  type: LoadBalancer