apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: connect_configs
        - name: OFFSET_STORAGE_TOPIC
          value: connect_offsets
        - name: STATUS_STORAGE_TOPIC
          value: connect_statuses
        image: quay.io/debezium/connect:3.2
        imagePullPolicy: Always
        name: debezium-connect
        ports:
        - containerPort: 8083
          protocol: TCP
        resources: {}